<a href="https://colab.research.google.com/github/Das0908/pytorch-tutorial/blob/main/pytorch_tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [2]:
t1 = torch.tensor(4.)

In [6]:
#vector
t2 = torch.tensor([1. , 2,3,4,5])
t2

tensor([1., 2., 3., 4., 5.])

In [7]:
#matrix
t3 = torch.tensor([[5. ,6] , [7,8] , [9 , 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [9]:
#3 dimensional array
t4 = torch.tensor([
      [[11 , 12, 13] ,
       [14 ,15. , 16],
       [17 ,18 , 19]]
])
t4

tensor([[[11., 12., 13.],
         [14., 15., 16.],
         [17., 18., 19.]]])

In [15]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.6.0
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3


In [2]:
import numpy as np

In [2]:
np1 = np.random.rand(3,4)
np1

array([[0.34569674, 0.74770563, 0.73111544, 0.76004358],
       [0.09765379, 0.48062699, 0.64357981, 0.66851054],
       [0.48825726, 0.76791406, 0.90776365, 0.00772553]])

In [9]:
t6 = torch.tensor(np1)
t6

tensor([[0.3457, 0.7477, 0.7311, 0.7600],
        [0.0977, 0.4806, 0.6436, 0.6685],
        [0.4883, 0.7679, 0.9078, 0.0077]], dtype=torch.float64)

In [10]:
t6.dtype

torch.float64

In [5]:
my_torch = torch.arange(12)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
#RESHAPE AND VIEW
my_torch = my_torch.reshape(2,2,3)
my_torch

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [ ]:
# RESHAPE IF WE DONT KNOW THE NUMBER OF ITEMS USING -1  // only one dimension can be infered

In [9]:
mytorch2 = torch.zeros(15)
mytorch2

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
mytorch2 = mytorch2.reshape(3,-1)
mytorch2

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [16]:
mytorch2 = mytorch2.reshape(-1, 5 , 3)   # reshape and view methods are exactly same , implementation and syntax wise
mytorch2

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [17]:
# with reshape and view , changes to original tensor re updated automatically
my_torch5 = torch.arange(16)
my_torch5

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
my_torch6 = my_torch5.reshape(4,-1)

In [23]:
my_torch5[1] = 120

In [24]:
my_torch6

tensor([[  0, 120,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]])

In [49]:
#slicing
my_torch7 = torch.arange(12)
my_torch7

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
my_torch8 = my_torch7.reshape(4,-1)
my_torch8

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [57]:
my_torch8[:,2:]

tensor([[ 2],
        [ 5],
        [ 8],
        [11]])

In [58]:
#MATH OPERATIONS WITH TENSOR

In [59]:
torch1 = torch.tensor([1 ,2, 3, 4, 5])
torch2 = torch.arange(5 , 10)

In [62]:
#add
torch1 + torch2

tensor([ 6,  8, 10, 12, 14])

In [65]:
#add longhand
torch.add(torch1 , torch2)
torch1.add(torch2)

tensor([ 6,  8, 10, 12, 14])

In [66]:
#sub
print(torch2-torch1)
#sub longhand
print(torch.sub(torch2 , torch1))

tensor([4, 4, 4, 4, 4])
tensor([4, 4, 4, 4, 4])


In [67]:
#mul
print(torch1*torch2)
#mul longhand
print(torch1.mul(torch2))

tensor([ 5, 12, 21, 32, 45])
tensor([ 5, 12, 21, 32, 45])


In [68]:
#div
print(torch2 / torch1)
# longhand
print(torch.div(torch2 , torch1))

tensor([5.0000, 3.0000, 2.3333, 2.0000, 1.8000])
tensor([5.0000, 3.0000, 2.3333, 2.0000, 1.8000])


In [69]:
#modulus
print( torch2 % torch1)
#remainder
print(torch.remainder(torch2 , torch1))

tensor([0, 0, 1, 0, 4])
tensor([0, 0, 1, 0, 4])


In [71]:
#reassignment
torch1 = torch1 + torch2
print(torch1)
#or ( use'_')
torch1.add_(torch2)
print(torch1)

tensor([11, 14, 17, 20, 23])
tensor([16, 20, 24, 28, 32])
